apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: uploader
  namespace: uploader
spec:
  host: uploader.apps.octo-emerging.redhataicoe.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: uploader
    weight: 100
  wildcardPolicy: None
