---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploader-pvc
  namespace: uploader
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: kubevirt-hostpath-provisioner 
  resources:
    requests:
      storage: 20Gi
